{
 "title": "System Metrics",
 "description": "Ubuntu Docker VM 102",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   },
   { "name": "period", "query": "day,week,month,year,range" }
  ]
 },
 "panels": [
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Docker Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_cpu\" WHERE (\"docker.group\" =~ /^()$/ AND \"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Swarm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"n_cpus\") FROM \"docker\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Docker Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"n_images\") FROM \"docker\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Core 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu0" }
     ]
    },
    {
     "alias": "Core 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu1" }
     ]
    },
    {
     "alias": "Core 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT distinct(\"usage_idle\") *-1+100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu2" }
     ]
    },
    {
     "alias": "Core 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT distinct(\"usage_idle\") *-1+100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu3" }
     ]
    },
    {
     "alias": "Core 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT distinct(\"usage_idle\") *-1+100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu4" }
     ]
    },
    {
     "alias": "Core 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT distinct(\"usage_idle\") *-1+100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu5" }
     ]
    },
    {
     "alias": "Core 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT distinct(\"usage_idle\") *-1+100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu6" }
     ]
    },
    {
     "alias": "Core 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT distinct(\"usage_idle\") *-1+100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu7" }
     ]
    },
    {
     "alias": "CPU Average",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as short,mean(load5) as medium,mean(load15) as long FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}