apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-scene-secrets-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-intersection-pgserver-media
  namespace: smart-intersection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi