apiVersion: v1
kind: Service
metadata:
  name: vdms
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-vdms
  ports:
  - name: "55555"
    protocol: TCP
    port: 55555
    targetPort: 55555
