# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update actions on a monthly interval
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      github-actions-dependency:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "metro-ai-suite/interactive-digital-avatar"
    schedule:
      interval: "monthly"
    groups:
      other-python:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-multimodal/classification-training"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-multimodal-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-multimodal/vlm-fine-tuning"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-multimodal-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-multimodal/ui-service"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-multimodal-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-multimodal/insights-workbench"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-multimodal-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-multimodal/weld-data-simulator"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-multimodal-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-multimodal/fusion-analytics"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-multimodal-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-multimodal/tests"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-multimodal-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-time-series"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-time-series-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-time-series/apps/wind-turbine-anomaly-detection/training"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-time-series-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-time-series/simulator/opcua-server"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-time-series-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-time-series/simulator/mqtt-publisher"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-time-series-python:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/manufacturing-ai-suite/industrial-edge-insights-time-series/tests"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      industrial-edge-insights-time-series-python:
        applies-to: version-updates
        patterns:
          - "*"