{{- $svc := .Values.services.rppg | default dict }}
{{- if and $svc.enabled ($svc.service | default dict).enabled }}

apiVersion: v1
kind: Service
metadata:
  name: rppg
  namespace: {{ $.Values.namespace }}
spec:
  type: {{ $svc.service.type | default "ClusterIP" }}
  selector:
    app: rppg
  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.containerPort }}

{{- end }}
