{
 "title": "Smart Toll - Vehicle Events & Axle Analysis",
 "time": { "from": "2026-06-24T07:02:05.505Z", "to": "2026-06-25T07:02:05.505Z" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "plate", "query": "GZ142N" },
   {
    "name": "image",
    "query": "/images/vehicle-events/2026-06-25/test/plate_front_GZ142N_000126.jpg"
   },
   { "name": "axles" },
   { "name": "speed", "query": "0.55 km/h" },
   { "name": "dwell", "query": "13.67 s" },
   { "name": "toll_class", "query": "No Class" },
   { "name": "toll_fee", "query": "0" },
   {
    "name": "scene",
    "label": "scene",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"smart-toll-bucket\",\n  tag: \"scene_name\"\n)\n"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"smart-toll-bucket\",\n  tag: \"region_name\"\n)\n"
    }
   },
   {
    "name": "vehicle_img",
    "query": "/images/vehicle-events/2026-06-25/test/vehicle_front_9_000126.jpg"
   }
  ]
 },
 "panels": [
  {
   "title": "Vehicle Events Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n \n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\"\n  )\n \n  |> pivot(\n      rowKey: [\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n \n  |> filter(fn: (r) =>\n      exists r.license_plate_text and\n      r.license_plate_text != \"\"\n  )\n \n  |> filter(fn: (r) =>\n      exists r.front_plate_image_url or\n      exists r.rear_plate_image_url or\n      exists r.vehicle_front_image_url or\n      exists r.vehicle_rear_image_url\n  )\n \n  |> map(fn: (r) => ({\n \n      _time: r._time,\n      roi_name: r.region_name,\n      license_plate_text: r.license_plate_text,\n      axles: r.axle_count,\n      speed: string(v: r.speed) + \" km/h\",\n      dwell: string(v: r.dwell) + \" s\",\n      image_url:\n \n        if exists r.front_plate_image_url\n \n        then r.front_plate_image_url\n \n        else if exists r.rear_plate_image_url\n \n        then r.rear_plate_image_url\n \n        else \"\",\n \n      vehicle_image_url:\n \n        if exists r.vehicle_front_image_url\n \n        then r.vehicle_front_image_url\n \n        else if exists r.vehicle_rear_image_url\n \n        then r.vehicle_rear_image_url\n \n        else \"\",\n \n      toll_class:\n \n        if r.axle_count < 3 then \"Light\"\n \n        else if r.axle_count == 3 then \"Medium\"\n \n        else if r.axle_count > 3 then \"Heavy\"\n \n        else \"No Class\",\n \n      toll_fee:\n \n        if r.axle_count < 3 then 10\n \n        else if r.axle_count == 3 then 15\n \n        else if r.axle_count > 3 then 20\n \n        else 0\n \n  }))\n \n  |> keep(columns: [\n \n      \"_time\",\n \n      \"license_plate_text\",\n \n      \"axles\",\n \n      \"toll_class\",\n \n      \"toll_fee\",\n \n      \"speed\",\n \n      \"dwell\",\n \n      \"roi_name\",\n \n      \"image_url\",\n \n      \"vehicle_image_url\"\n \n  ])\n \n  |> sort(columns: [\"_time\"], desc: true)"
    }
   ]
  },
  {
   "title": "Vehicle Stats",
   "type": "text",
   "description": "Details of the Vehicle",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<div style=\"\n  display: grid;\n  grid-template-columns: 1fr 1.2fr;\n  padding: 2px;\n  align-items: left;\n\">\n\n\n  <!-- RIGHT: IMAGE -->\n  <div style=\"\n    text-align:center;\n    background: rgba(255,255,255,0.03);\n    border-radius: 10px;\n    padding: 12px;\n  \">\n    <h3 style=\"margin-bottom: 10px; color:#a5d6a7;\">\n       License Plate Image\n    </h3>\n\n    <img\n      src=\"${image}\"\n      style=\"\n        width: 250px;\n        max-height: 420px;\n        border-radius: 8px;\n        border: 1px solid rgba(255,255,255,0.1);\n      \"\n      alt=\"License Plate Image\"\n    />\n <h3 style=\"margin-bottom: 10px; color:#a5d6a7;\">\n       Vehicle Image\n    </h3>\n\n    <img\n      src=\"${vehicle_img}\"\n      style=\"\n        width: 250px;\n        max-height: 420px;\n        border-radius: 8px;\n        border: 1px solid rgba(255,255,255,0.1);\n      \"\n      alt=\"Vehilce Image\"\n    />\n\n    <div style=\"margin-top:8px; font-size:12px; color:#777;\">\n      Click another row to update\n    </div>\n  </div>\n  <!-- LEFT: VEHICLE STATS -->\n  <div style=\"\n    background: rgba(255,255,255,0.03);\n    border-radius: 10px;\n    padding: 10px;\n  \">\n    <h4 style=\"margin-bottom: 2px; color:#90caf9;\">\n      Vehicle Details\n    </h4>\n\n    <table style=\"width:100%; border-collapse: collapse; font-size:12px;\">\n      <tr>\n        <td style=\"padding:6px; color:#aaa;\">License Plate</td>\n        <td style=\"padding:6px; font-weight:bold;\">${plate}</td>\n      </tr>\n      <!-- <tr>\n        <td style=\"padding:6px; color:#aaa;\">Axles </td>\n        <td style=\"padding:6px;\">${axles}</td>\n      </tr> -->\n      <tr>\n        <td style=\"padding:6px; color:#aaa;\">Toll Class </td>\n        <td style=\"padding:6px;\">${toll_class}</td>\n      </tr>\n      <tr>\n        <td style=\"padding:6px; color:#aaa;\">Toll Fee</td>\n        <td style=\"padding:6px;\">$${toll_fee}</td>\n      </tr>\n      <tr>\n        <td style=\"padding:6px; color:#aaa;\">Speed</td>\n        <td style=\"padding:6px;\">${speed}</td>\n      </tr>\n        <tr>\n        <td style=\"padding:6px; color:#aaa;\">Dwell</td>\n        <td style=\"padding:6px;\">${dwell} s</td>\n      </tr>\n    </table>\n  </div>\n\n\n\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"\n  padding:5px;\n  border-left:4px solid #1f78c1;\n  background-color:#111827;\n  color:#e5e7eb;\n  font-size:14px;\n\">\n  ℹ️ <b>Note:</b> Click on the <b>Plate No</b> in the table above to view\n  vehicle details, toll class, fee, and license plate image.\n</div>\n"
   }
  },
  {
   "title": "Axle Count",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"axle_count\" and\n      r._value >= 2 and\n      r.scene_name == \"${scene}\"\n  )\n\n  // create categorical label + counter\n  |> map(fn: (r) => ({\n      axles: \"Axle-\" + string(v: r._value),\n      vehicle_count: 1\n  }))\n\n  // aggregate\n  |> group(columns: [\"axles\"])\n  |> sum(column: \"vehicle_count\")\n\n  // 🔑 REQUIRED: ungroup for Grafana bar chart\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Axle-Wise Toll Revenue",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r.scene_name == \"${scene}\" \n  )\n\n  // bring axle_count into rows\n  |> pivot(\n      rowKey: [\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n\n  // keep only valid axle detections\n  |> filter(fn: (r) =>\n      exists r.axle_count and\n      r.axle_count > 0\n  )\n\n  // compute axle class and toll fee\n  |> map(fn: (r) => ({\n      vehicle_class:\n        if r.axle_count < 3 then \"Light\"\n        else if r.axle_count == 3 then \"Medium\"\n        else \"Heavy\",\n\n      toll_fee:\n        if r.axle_count < 3 then 10\n        else if r.axle_count == 3 then 15\n        else 20\n  }))\n\n  // aggregate revenue per axle class\n  |> group(columns: [\"vehicle_class\"])\n  |> sum(column: \"toll_fee\")\n\n  // 🔑 required for Grafana bar chart\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Vehicle History",
   "type": "table",
   "description": "Same Plate",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: -7d)\n\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r.scene_name == \"${scene}\" \n  )\n\n  |> pivot(\n      rowKey: [\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n\n  // filter AFTER pivot\n  |> filter(fn: (r) =>\n      exists r.license_plate_text and\n      r.license_plate_text == \"${plate}\"\n  )\n\n  |> map(fn: (r) => ({\n      _time: r._time,\n      roi_name: r.region_name,\n      axless: r.axle_count\n  }))\n\n  |> keep(columns: [\n      \"_time\",\n      \"roi_name\",\n      \"axless\"\n  ])\n\n  |> sort(columns: [\"_time\"], desc: true)\n"
    }
   ]
  }
 ]
}