# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "wpd"
displayName: "wpd"
description: "Weld Porosity Detection Sample Application"
version: "1.1.0"

applications:
  - name: wpd-app
    version: 1.1.0

defaultNamespaces:
  wpd-app: wpd

deploymentProfiles:
  - name: "default"
    applicationProfiles:
      - application: "wpd-app"
        profile: "default"
  - name: "with-intel-gpu-extension"
    applicationProfiles:
      - application: "wpd-app"
        profile: "with-intel-gpu-extension"
  - name: "without-intel-gpu-extension"
    applicationProfiles:
      - application: "wpd-app"
        profile: "without-intel-gpu-extension"
