version: "3"

services:
  broker:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt_broker
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - app_network

  dlstreamer-pipeline-server:
    image: intel/dlstreamer-pipeline-server:3.0.0
    container_name: dlstreamer-pipeline-server
    ports:
    - '8080:8080'
    - '8554:8554'
    environment:
      - ENABLE_WEBRTC=true
      - no_proxy=${no_proxy},${HOST_IP}
      - WEBRTC_SIGNALING_SERVER=http://${HOST_IP}:8889
      - http_proxy=${http_proxy}
      - APPEND_PIPELINE_NAME_TO_PUBLISHER_TOPIC=true
      - https_proxy=${https_proxy}
      - RUN_MODE=EVA
      - EMIT_SOURCE_AND_DESTINATION=true
      - REST_SERVER_PORT=8080
      - SERVICE_NAME=dlstreamer-pipeline-server
    volumes:
      - vol_dlsps_pipeline_root:/var/cache/pipeline_root:uid=1999,gid=1999
      - "./dlsps/models:/home/pipeline-server/models"
      - "./dlsps/videos:/home/pipeline-server/videos"
      - "./dlsps/config.json:/home/pipeline-server/config.json"
      - "/run/udev:/run/udev:ro"
      - "/dev:/dev"
      - "/tmp:/tmp"
    group_add:
      - "109"
      - "110"
      - "992"
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 209:* rmw'
      - 'a 189:* rwm'
    devices:
      - "/dev:/dev"
    networks:
    - app_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
  
  mediamtx:
    image: bluenviron/mediamtx:1.11.3
    container_name: mediamtx-server
    environment:
      - MTX_LOGLEVEL=debug
      - MTX_RTSP=no
      - MTX_RTMP=no
      - MTX_HLS=no
      - MTX_SRT=no
      - MTX_WEBRTCICESERVERS2_0_URL=turn:${HOST_IP}:3478
      - MTX_WEBRTCICESERVERS2_0_USERNAME=myusername
      - MTX_WEBRTCICESERVERS2_0_PASSWORD=mypassword
    ports:
      - "8889:8889"
      - "8189:8189"
      - "9997:9997"
    networks:
    - app_network

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    command: ["-v"]  # Verbose mode for logging
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
      - "./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/test_plugin:/var/lib/grafana/plugins/intel-custom-panel"
    networks:
      - app_network
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,ryantxu-ajax-panel,grafana-mqtt-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=intel-custom-panel

  node-red:
    image: nodered/node-red
    container_name: node-red
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    volumes:
      - "./node-red:/data"
      - "./dlsps/videos:/data/public/videos"
    ipc: "none"
    entrypoint: [ "/bin/bash", "-c", "/data/install_package.sh && /usr/src/node-red/entrypoint.sh" ]
    user: root
    networks:
      - app_network
    ports:
      - "1880:1880"

networks:
  app_network:
    driver: "bridge"

volumes:
  vol_dlsps_pipeline_root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
