{
 "title": "Anthem-ITS-Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "South Bound lane - Vehicle Count",
   "type": "bargauge",
   "description": "West Bound lane - dwell time",
   "gridPos": { "h": 9, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"SBLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "South Bound lane - dwell time",
   "type": "gauge",
   "description": "West Bound lane - dwell time",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"SBLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Jwalking",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"pedestrian\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NOPED\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "SBEBLTLANE- Vehicle Count",
   "type": "bargauge",
   "description": "SBEBLTLANE - count",
   "gridPos": { "h": 9, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"SBEBLTLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SBEBLTLANE - dwell time",
   "type": "gauge",
   "description": "SBEBLTLANE - dwell time",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"SBEBLTLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "West Bound lane - Vehicle Count",
   "type": "bargauge",
   "description": "West Bound lane - dwell time",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"WBLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "West Bound lane - dwell time",
   "type": "gauge",
   "description": "West Bound lane - dwell time",
   "gridPos": { "h": 11, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"WBLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "North crosswalk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"pedestrian\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NCWLK\")"
    }
   ]
  },
  {
   "title": "EBNBLTLANE - Vehicle Count",
   "type": "bargauge",
   "description": "EBNBLTLANE - dwell time",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"EBNBLTLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EBNBLTLANE - dwell time",
   "type": "gauge",
   "description": "EBNBLTLANE - dwell time",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"EBNBLTLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ECWLK",
   "type": "stat",
   "gridPos": { "h": 18, "w": 1, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"pedestrian\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"ECWLK\")"
    }
   ]
  },
  {
   "title": "Active VRU location",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 6, "x": 7, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pedestrian_loc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pedid\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"latitude\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()  \r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\r\n"
    }
   ]
  },
  {
   "title": "WCWLK",
   "type": "stat",
   "gridPos": { "h": 18, "w": 1, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"pedestrian\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"WCWLK\")"
    }
   ]
  },
  {
   "title": "East Bound lane - Vehicle Count",
   "type": "bargauge",
   "description": "EAST Bound lane - dwell time",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"EBLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "East Bound lane - dwell time",
   "type": "gauge",
   "description": "EAST Bound lane - dwell time",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"EBLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "WBNBRTLANE - Vehicle Count",
   "type": "bargauge",
   "description": "Westbound to northbound Right turn lane - Vehicle count",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"WBNBRTLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "WBNBRTLANE - dwell time",
   "type": "gauge",
   "description": "WBNBRTLANE - dwell time",
   "gridPos": { "h": 11, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"WBNBRTLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EBSBRTLANE - Vehicle Count",
   "type": "bargauge",
   "description": "EBSBRTLANE - dwell time",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"EBSBRTLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EBSBRTLANE - dwell time",
   "type": "gauge",
   "description": "EBSBRTLANE  - dwell time",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"EBSBRTLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SCWLK",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"pedestrian\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"SCWLK\")"
    }
   ]
  },
  {
   "title": "NBEBRTLANE - Vehicle Count",
   "type": "bargauge",
   "description": "NBEBRTLANE - Vehicle Count",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NBEBRTLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "North Bound lane - Vehicle Count",
   "type": "bargauge",
   "description": "North Bound lane - Vehicle Count",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NBLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "NBWBLTLANE - Vehicle Count",
   "type": "bargauge",
   "description": "NBWBLTLANE - Vehicle Count",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_count_2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NBWBLTLANE\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "NBWBLTLANE - dwell time",
   "type": "gauge",
   "description": "NBWBLTLANE - dwell time",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NBWBLTLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "North Bound lane - dwell time",
   "type": "gauge",
   "description": "North Bound lane - dwell time",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NBLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "NBEBRTLANE - dwell time",
   "type": "gauge",
   "description": "NBEBRTLANE - dwell time",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SS-Anthem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"region_obj_dwell_2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dwell_time\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Anthem\")\r\n  |> filter(fn: (r) => r[\"object\"] == \"vehicle\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"NBEBRTLANE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}