{
 "title": "Smart Toll - Overview",
 "time": { "from": "now-15d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scene",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"smart-toll-bucket\",\n  tag: \"scene_name\"\n)\n"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"smart-toll-bucket\",\n  tag: \"region_name\"\n)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div >\n  <h1 style=\"text-align:center;\">Smart Toll - Overview </h1>\n</div>"
   }
  },
  {
   "title": "Total Vehicles",
   "type": "stat",
   "description": "Number of Vehicles ",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"license_plate_text\"\n  )\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Vehicles(Last 1 Hour)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"license_plate_text\"\n  )\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "License Plates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"license_plate_text\"\n  )\n  |> group()\n  |> distinct(column: \"_value\")\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Average Speed(km/h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"speed\"\n  )\n  |> group()\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Average Dwell Times",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"dwell\" and\n      r.scene_name == \"${scene}\" \n  )\n  |> group()\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Heavy Vehicles (Axles ≥ 3)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"axle_count\" and\n      r._value >= 3 and\n      r.scene_name == \"${scene}\" \n  )\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Speed Violations (> 65 km/h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"speed\" and\n      r._value > 65 and\n      r.scene_name == \"${scene}\" and\n      r.region_name == \"${region}\"\n  )\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Average Axles per Vehicle",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\nfrom(bucket: \"smart-toll-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"axle_count\" and\n      r._value >= 2 and\n      r.scene_name == \"${scene}\"\n      \n  )\n  |> group()\n  |> mean()\n  |> map(fn: (r) => ({\n      r with _value: math.round(x: r._value)\n  }))"
    }
   ]
  },
  {
   "title": "Traffic Trend(Vehicles/30Min)",
   "type": "barchart",
   "description": "Number of Vehicles passed for every 30minutes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"smart-toll-bucket\")\n  |> range(start: -12h)\n  |> filter(fn: (r) =>\n      r._measurement == \"smart_tolling_events\" and\n      r._field == \"license_plate_text\" and\n      r.scene_name == \"${scene}\" \n  )\n  |> aggregateWindow(every: 30m, fn: count)\n  |> group()\n"
    }
   ]
  }
 ]
}