# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  # Apply only with RI versions that define nginx.
  nginx:
    container_name: ${INTERSECTION_NAME:-trafficagent}-nginx-reverse-proxy
