# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

services:
  ovms-service:
    devices:
      - "/dev/vfio/${VFIO_GROUP}:/dev/vfio/${VFIO_GROUP}"
    annotations:
      io.katacontainers.config.hypervisor.default_memory: "4096"
      io.katacontainers.config.hypervisor.enable_virtio_mem: "true"
      io.katacontainers.config.hypervisor.hot_plug_vfio: "root-port"
      io.katacontainers.config.hypervisor.pcie_root_port: "1"
