{{- $svc := .Values.services.mdpnp | default dict }}
{{- if and $svc.enabled ($svc.service | default dict).enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mdpnp
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.services.mdpnp.service.type | default "ClusterIP" }}
  selector:
    app: mdpnp
  ports:
    - port: {{ .Values.services.mdpnp.containerPort }}
      targetPort: {{ .Values.services.mdpnp.containerPort }}
{{- end }}
