{{- $svc := .Values.services.mdpnp | default dict }}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdpnp
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mdpnp.replicas }}
  selector:
    matchLabels:
      app: mdpnp
  template:
    metadata:
      labels:
        app: mdpnp
    spec:
      hostNetwork: {{ .Values.mdpnp.hostNetwork | default false }}
      containers:
        - name: mdpnp
          image: {{ include "health-ai.image" (dict "image" .Values.mdpnp.image) }}
          imagePullPolicy: IfNotPresent
{{- end }}
