{{- $svc := .Values.services.ddsBridge | default dict }}
{{- if and ($svc.enabled | default false) (($svc.service | default dict).enabled | default true) }}
apiVersion: v1
kind: Service
metadata:
  name: dds-bridge
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: dds-bridge
  ports:
    - name: dds
      port: {{ .Values.ddsBridge.servicePort }}
      targetPort: {{ .Values.ddsBridge.servicePort }}
{{- end }}