apiVersion: v1
data:
  MILVUS_URL: '{{ include "search_image_by_image.fullname" . }}-milvusdb:19530'
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 4dd006301f669d044c60fd579bb24fb08133f26f
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "search_image_by_image.labels" . | nindent 4 }}
    katenary.v3/component: milvusui
  name: '{{ include "search_image_by_image.fullname" . }}-milvusui'
