{
 "title": "Weld Defect Detection Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Anomaly Prediction for Weld Sensor Data (Primary Weld Current vs time)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Non Anomalous ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weld-sensor-anomaly-data",
     "query": "SELECT \"Primary Weld Current\" FROM \"autogen\".\"weld-sensor-anomaly-data\" WHERE (\"anomaly_status\"= 0) AND $timeFilter",
     "select": [
      [
       { "params": [ "Primary Weld Current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "anomaly_status::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Anomalous",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "weld-sensor-anomaly-data",
     "query": "SELECT \"Primary Weld Current\"  FROM \"autogen\".\"weld-sensor-anomaly-data\" WHERE (\"anomaly_status\"= 1)  AND $timeFilter",
     "select": [
      [
       { "params": [ "Primary Weld Current" ], "type": "field" }
      ]
     ],
     "source": "url",
     "tags": [
      { "key": "anomaly_status::field", "operator": "=", "value": "1" }
     ],
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Anomaly Detected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weld-sensor-anomaly-data",
     "query": "SELECT count(\"Pressure\") FROM \"weld-sensor-anomaly-data\" where anomaly_status>0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Ingested Points",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(Feed) AS mean_value FROM \"weld-sensor-data\"\n"
    }
   ]
  },
  {
   "title": "Total Processed Points",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weld-analytics-data",
     "query": "SELECT count(\"Feed\") FROM \"weld-sensor-anomaly-data\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simulation vs Prediction",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Simulator Category",
     "query": "SELECT \"filename\" FROM \"weld-sensor-anomaly-data\" WHERE $timeFilter order by time desc"
    },
    {
     "alias": "Predicted Category",
     "query": "SELECT \"predicted_category\" FROM \"weld-sensor-anomaly-data\" WHERE $timeFilter order by time desc"
    }
   ]
  },
  {
   "title": "Ingestion Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(\"Pressure\") AS mean_value FROM \"weld-sensor-data\"  WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Average Time to Process a point E2E (seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT mean(end_end_time)/1000000000 AS mean_value FROM \"weld-sensor-anomaly-data\" WHERE  time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(\"Pressure\") AS mean_value FROM \"weld-sensor-anomaly-data\" WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Time (seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": " select mean(processing_time)/1000000000 from \"weld-sensor-anomaly-data\" order by time desc"
    }
   ]
  }
 ]
}