---
# Source: health-ai-suite/templates/ai-ecg/pvc-ai-ecg.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ai-ecg
  namespace: health-ai
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
# Source: health-ai-suite/templates/pose/pvc-pose.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pose
  namespace: health-ai
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
# Source: health-ai-suite/templates/rppg/pvc-rppg.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rppg
  namespace: health-ai
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
# Source: health-ai-suite/templates/aggregator/aggregator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aggregator
  namespace: health-ai
spec:
  type: ClusterIP
  selector:
    app: aggregator
  ports:
    - port: 50051
      targetPort: 50051
---
# Source: health-ai-suite/templates/ai-ecg/ai-ecg-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ai-ecg
  namespace: health-ai
spec:
  type: ClusterIP
  selector:
    app: ai-ecg
  ports:
    - port: 8000
      targetPort: 8000
---
# Source: health-ai-suite/templates/dds-bridge/dds-bridge-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dds-bridge
  namespace: health-ai
spec:
  type: ClusterIP
  selector:
    app: dds-bridge
  ports:
    - name: dds
      port: 8082
      targetPort: 8082
---
# Source: health-ai-suite/templates/metrics/metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: health-ai
spec:
  type: ClusterIP
  selector:
    app: metrics
  ports:
    - port: 9000
      targetPort: 9000
---
# Source: health-ai-suite/templates/aggregator/aggregator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  namespace: health-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: aggregator
          image: intel/hl-ai-aggregator-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
---
# Source: health-ai-suite/templates/ai-ecg/ai-ecg-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ecg
  namespace: health-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-ecg
  template:
    metadata:
      labels:
        app: ai-ecg
    spec:
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: pvc-ai-ecg
      containers:
        - name: ai-ecg
          image: intel/hl-ai-ecg:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: assets
              mountPath: /app/models
---
# Source: health-ai-suite/templates/dds-bridge/dds-bridge-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dds-bridge
  namespace: health-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dds-bridge
  template:
    metadata:
      labels:
        app: dds-bridge
    spec:
      containers:
        - name: dds-bridge
          image: intel/hl-ai-dds-bridge:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
# Source: health-ai-suite/templates/mdpnp/mdpnp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdpnp
  namespace: health-ai
spec:
  replicas: 
  selector:
    matchLabels:
      app: mdpnp
  template:
    metadata:
      labels:
        app: mdpnp
    spec:

      containers:
        - name: mdpnp
          image: 
          imagePullPolicy: IfNotPresent
---
# Source: health-ai-suite/templates/metrics/metrics-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: health-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - name: metrics
          image: intel/hl-ai-metrics-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
---
# Source: health-ai-suite/templates/pose/pose-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pose
  namespace: health-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pose
  template:
    metadata:
      labels:
        app: pose
    spec:
      containers:
        - name: pose
          image: 
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: pose-assets
              mountPath: /app/models
            - name: pose-assets
              mountPath: /videos/pose

      volumes:
        - name: pose-assets
          persistentVolumeClaim:
            claimName: pvc-pose
---
# Source: health-ai-suite/templates/rppg/rppg-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rppg
  namespace: health-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rppg
  template:
    metadata:
      labels:
        app: rppg
    spec:
      containers:
        - name: rppg
          image: 
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: rppg-assets
              mountPath: /models/rppg
            - name: rppg-assets
              mountPath: /videos/rppg

      volumes:
        - name: rppg-assets
          persistentVolumeClaim:
            claimName: pvc-rppg
---
# Source: health-ai-suite/templates/assets-downloader/assets-downloader-ai-ecg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: assets-downloader-ai-ecg
  namespace: health-ai
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: downloader
          image: intel/hl-ai-assets-downloader:1.0.0
          volumeMounts:
            - name: assets
              mountPath: /data
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: pvc-ai-ecg
---
# Source: health-ai-suite/templates/assets-downloader/assets-downloader-pose-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: assets-downloader-pose
  namespace: health-ai
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: downloader
          image: intel/hl-ai-assets-downloader:1.0.0
          volumeMounts:
            - name: assets
              mountPath: /data
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: pvc-pose
---
# Source: health-ai-suite/templates/assets-downloader/assets-downloader-rppg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: assets-downloader-rppg
  namespace: health-ai
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: downloader
          image: intel/hl-ai-assets-downloader:1.0.0
          volumeMounts:
            - name: assets
              mountPath: /data
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: pvc-rppg
