namespace: health-ai

global:
  imageRegistry: intel
  imageTag: "1.0.0"
  imagePullPolicy: Never

assetsDownloader:
  enabled: true
  image:
    registry: intel
    name: hl-ai-assets-downloader
    tag: "1.0.0"
    pullPolicy: Never

services:
  aiEcg:
    enabled: true
    service:
      enabled: true

  pose:
    enabled: true
    service:
      enabled: false

  rppg:
    enabled: true
    service:
      enabled: false

  mdpnp:
    enabled: true
    service:
      enabled: false

  aggregator:
    enabled: true
    service:
      enabled: true

  ddsBridge:
    enabled: true
    service:
      enabled: true

  metrics:
    enabled: true
    service:
      enabled: true

aiEcg:
  image:
    registry: intel
    name: hl-ai-ecg
    tag: "1.0.0"
    pullPolicy: Never
  replicas: 1
  servicePort: 8000

pose:
  image:
    registry: intel
    name: hl-ai-3dpose
    tag: "1.0.0"
    pullPolicy: Never
  replicas: 1

rppg:
  image:
    registry: intel
    name: hl-ai-rppg-service
    tag: "1.0.0"
    pullPolicy: Never
  replicas: 1

mdpnp:
  image:
    registry: intel
    name: hl-ai-mdpnp
    tag: "1.0.0"
    pullPolicy: Never
  replicas: 1
  hostNetwork: true

aggregator:
  image:
    registry: intel
    name: hl-ai-aggregator-service
    tag: "1.0.0"
    pullPolicy: Never
  replicas: 1
  servicePort: 50051

ddsBridge:
  image:
    registry: intel
    name: hl-ai-dds-bridge
    tag: "1.0.0"
    pullPolicy: Never
  replicas: 1
  servicePort: 8082

metrics:
  image:
    registry: intel
    name: hl-ai-metrics-service
    tag: "1.0.0"
    pullPolicy: Never
  replicas: 1
  servicePort: 9000
