{{/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.liveMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stia.liveMetrics.fullname" . }}
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: live-metrics
spec:
  replicas: {{ .Values.liveMetrics.replicas }}
  selector:
    matchLabels:
      app: {{ include "stia.liveMetrics.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "stia.liveMetrics.fullname" . }}
        {{- include "stia.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: live-metrics
    spec:
      containers:
        - name: {{ .Values.liveMetrics.name }}
          image: "{{ .Values.liveMetrics.image.repository }}:{{ .Values.liveMetrics.image.tag }}"
          imagePullPolicy: {{ .Values.liveMetrics.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: METRICS_PORT
              value: {{ .Values.liveMetrics.env.metricsPort | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.liveMetrics.env.logLevel | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.liveMetrics.env.corsOrigins | quote }}
            - name: http_proxy
              value: {{ .Values.global.proxy.httpProxy | quote }}
            - name: https_proxy
              value: {{ .Values.global.proxy.httpsProxy | quote }}
            - name: no_proxy
              value: "{{ .Values.global.proxy.noProxy }},.svc,.svc.cluster.local,.cluster.local,{{ include "stia.collector.fullname" . }}"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.liveMetrics.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveMetrics.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.liveMetrics.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.liveMetrics.healthcheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.liveMetrics.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveMetrics.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.liveMetrics.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.liveMetrics.healthcheck.failureThreshold }}
          resources:
            {{- toYaml .Values.liveMetrics.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
{{- end }}
