{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $metricsManager := index .Values "metrics-manager" -}}
{{- if and $metricsManager.enabled $metricsManager.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stia.metricsManager.fullname" . }}
  {{- with $metricsManager.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-manager
    {{- with $metricsManager.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $metricsManager.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $metricsManager.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics-manager
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: telegraf
      interval: {{ $metricsManager.serviceMonitor.interval }}
      scrapeTimeout: {{ $metricsManager.serviceMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}
