{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $metricsManager := index .Values "metrics-manager" -}}
{{- if $metricsManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stia.metricsManager.fullname" . }}
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-manager
  {{- with $metricsManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $metricsManager.service.type }}
  selector:
    app: {{ include "stia.metricsManager.fullname" . }}
    app.kubernetes.io/component: metrics-manager
  ports:
    - name: metrics
      port: {{ $metricsManager.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      {{- if and (eq $metricsManager.service.type "NodePort") $metricsManager.service.nodePorts.metrics }}
      nodePort: {{ $metricsManager.service.nodePorts.metrics }}
      {{- end }}
    - name: telegraf
      port: {{ $metricsManager.service.telegrafPort }}
      targetPort: telegraf
      protocol: TCP
      {{- if and (eq $metricsManager.service.type "NodePort") $metricsManager.service.nodePorts.telegraf }}
      nodePort: {{ $metricsManager.service.nodePorts.telegraf }}
      {{- end }}
    - name: telegraf-http
      port: {{ $metricsManager.service.telegrafHttpPort }}
      targetPort: telegraf-http
      protocol: TCP
      {{- if and (eq $metricsManager.service.type "NodePort") $metricsManager.service.nodePorts.telegrafHttp }}
      nodePort: {{ $metricsManager.service.nodePorts.telegrafHttp }}
      {{- end }}
{{- end }}
