{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $metricsManager := index .Values "metrics-manager" -}}
{{- if and $metricsManager.enabled $metricsManager.pod.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stia.metricsManager.serviceAccountName" . }}
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-manager
  {{- with $metricsManager.pod.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
