services:

  mediaserver:
    image: bluenviron/mediamtx:1.14.0
    networks:
      scenescape:
        aliases:
          - mediaserver
    ports:
      - "8554:8554"
    restart: always
    pids_limit: 1000

  cams:
    image: linuxserver/ffmpeg:version-8.0-cli
    command: -nostdin -re -stream_loop -1 -i /data/1122east.ts -map 0:v -c copy -f rtsp -rtsp_transport udp ${INPUT_RTSP}
    volumes:
      - ${ROOT_DIR}/src/dlstreamer-pipeline-server/videos:/data
    networks:
      scenescape:
    depends_on:
      - mediaserver
    restart: always
    pids_limit: 1000

networks:
  scenescape:
    driver: "bridge"

volumes:
  dlstreamer-pipeline-server-pipeline-root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
