{
 "title": "metric_dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Data Points KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestion Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(wind_speed) AS mean_value FROM wind_turbine_data  WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(wind_speed) AS mean_value FROM wind_turbine_anomaly_data  WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Average Time to Process a point E2E (Seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (\n  SELECT mean(end_end_time)/1000000000 AS mean_value FROM wind_turbine_anomaly_data\n  WHERE analytic=1 and time > now() - 3m\n  GROUP BY time(1m)\n)\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Time (Seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": " select mean(processing_time)/1000000000 from wind_turbine_anomaly_data where analytic=1 order by time desc"
    }
   ]
  },
  { "title": "Other Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Anomaly Records",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Anomaly - 0.3",
     "query": "SELECT count(anomaly_status) FROM \"wind_turbine_anomaly_data\" WHERE (\"anomaly_status\" =  0.3) "
    },
    {
     "alias": "Anomaly - 0.6",
     "query": "SELECT count(anomaly_status) FROM \"wind_turbine_anomaly_data\" WHERE (\"anomaly_status\" =  0.6) "
    },
    {
     "alias": "Anomaly - 1",
     "query": "SELECT count(anomaly_status) FROM \"wind_turbine_anomaly_data\" WHERE (\"anomaly_status\" =  1) "
    }
   ]
  },
  {
   "title": "Total Ingested Points",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(wind_speed) AS mean_value FROM wind_turbine_data\n"
    }
   ]
  },
  {
   "title": "Total Processed Points",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(wind_speed) AS mean_value FROM wind_turbine_anomaly_data\n"
    }
   ]
  }
 ]
}