{
 "title": "Weld Anomaly Detection Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Anomaly Prediction for Grid Active Power",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"Pressure\", \"CO2 Weld Flow\", \"Primary Weld Current\" from \"weld-detection-anomaly-data\"",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_turbine_anomaly_data",
     "query": "SELECT \"Defective Weld\" FROM \"weld-detection-anomaly-data\" where anomaly_status>= 1",
     "select": [
      [
       { "params": [ "anomaly_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Anomaly Detected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wind_turbine_anomaly_data",
     "query": "SELECT count(\"Pressure\") FROM \"weld-detection-anomaly-data\" where anomaly_status>0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Ingested Points",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(Feed) AS mean_value FROM \"weld-detection-data\"\n"
    }
   ]
  },
  {
   "title": "Total Processed Points",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weld-analytics-data",
     "query": "SELECT count(\"Feed\") FROM \"weld-detection-anomaly-data\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingestion Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(\"Pressure\") AS mean_value FROM \"weld-detection-anomaly-data\"  WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Rate (Points Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT count(\"Pressure\") AS mean_value FROM \"weld-detection-anomaly-data\" WHERE time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Average Time to Process a point E2E (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(mean_value) FROM (SELECT mean(end_end_time)/1000000 AS mean_value FROM \"weld-detection-anomaly-data\" WHERE  time > now() - 3m GROUP BY time(1m))\n"
    }
   ]
  },
  {
   "title": "Analytics Processing Time (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": " select mean(processing_time)/1000000 from \"weld-detection-anomaly-data\" order by time desc"
    }
   ]
  }
 ]
}