---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Visual Search and QA] SDLe Scans - Scan Trivy Bandit Virus"
run-name: "[Visual Search and QA] SDLe Scans - Scan Trivy Bandit Virus"


# Only run at most 1 workflow concurrently per PR, unlimited for branches
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  workflow_dispatch:

jobs:   

  trivy-scan-job:
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@542607bc8b7adabaf67d9aed705077a701f59a66
        with:
          persist-credentials: false  

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true    
          android: true       
          dotnet: true        
          haskell: true       
          large-packages: true 
          docker-images: true 
          swap-storage: true  
      - name: Free Disk Space
        # You may pin to the exact commit or the version.
        # uses: ShubhamTatvamasi/free-disk-space-action@01128c655592f81375a0e0bb73d80031a2b44762
        uses: ShubhamTatvamasi/free-disk-space-action@559b7211811f3b7a54d07049da947649193f776d
          
      - name: Build Docker images
        run: |
          git clone https://github.com/open-edge-platform/edge-ai-libraries.git
          cd edge-ai-libraries/microservices
          docker build -t dataprep-visualdata-milvus:latest -f visual-data-preparation-for-retrieval/milvus/src/Dockerfile .
          docker build -t retriever-milvus:latest -f vector-retriever/milvus/src/Dockerfile .
          cd vlm-openvino-serving
          docker build -t vlm-openvino-serving:latest -f docker/Dockerfile .
          cd ../../..
          cd metro-ai-suite
          docker build -t visual-search-qa-app:latest -f visual-search-question-and-answering/src/Dockerfile .

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          scan-type: 'fs'
          format: 'template'
          template: 'html'
          output: 'trivy_fs_report.html'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          command: '--skip-dirs node_modules'

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          scan-type: 'image'
          image-ref: 'dataprep-visualdata-milvus:latest,retriever-milvus:latest,vlm-openvino-serving:latest,visual-search-qa-app:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Upload scan results
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: trivy-scan-results
          path: |
            trivy_fs_report.html
            trivy-results.sarif

  bandit-scans:
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    name: Run Bandit Scan
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ubuntu_version: ubuntu24
    steps:
    - name: Check out edge-ai-suites repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Run Bandit Scan
      run: |
        mkdir -p reports
        docker pull ghcr.io/pycqa/bandit/bandit
        echo "### Bandit Scan Results" >> $GITHUB_STEP_SUMMARY
        docker run --rm -v "${{ github.workspace }}:/src" ghcr.io/pycqa/bandit/bandit -r /src/metro-ai-suite/visual-search-question-and-answering/ -f txt -o /src/reports/bandit-report.txt || true >> $GITHUB_STEP_SUMMARY
        echo "Please find full report in bandit-report.txt" >> $GITHUB_STEP_SUMMARY
    - name: Upload Scan Reports
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: reports/bandit-report.txt
        
  virus-scans:
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    name: Run Virus Scan
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ubuntu_version: ubuntu24
    steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Run Virus Scan
      run: |
        mkdir -p reports
        docker pull clamav/clamav
        echo "### Virus Scan Results" >> $GITHUB_STEP_SUMMARY
        docker run --rm -v "${{ github.workspace }}:/src" clamav/clamav clamscan -r  /src/metro-ai-suite/visual-search-question-and-answering/ > ./reports/clamav-report.txt || true
        echo "Please find full report in clamav-report.txt" >> $GITHUB_STEP_SUMMARY
    - name: Upload Scan Reports
      uses: actions/upload-artifact@v4
      with:
        name: virus-reports
        path: reports/clamav-report.txt
    


