---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Visual Search and QA] SDLe Scans - Scan Trivy Bandit Virus"
run-name: "[Visual Search and QA] SDLe Scans - Scan Trivy Bandit Virus"


# Only run at most 1 workflow concurrently per PR, unlimited for branches
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  workflow_dispatch:

jobs:   

  trivy-scan-job:
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true    
          android: true       
          dotnet: true        
          haskell: true       
          large-packages: true 
          docker-images: true 
          swap-storage: true  
      - name: Free Disk Space
        # You may pin to the exact commit or the version.
        # uses: ShubhamTatvamasi/free-disk-space-action@01128c655592f81375a0e0bb73d80031a2b44762
        uses: ShubhamTatvamasi/free-disk-space-action@559b7211811f3b7a54d07049da947649193f776d
          
      - name: Build Docker images
        run: |
          git clone https://github.com/open-edge-platform/edge-ai-libraries.git
          cd edge-ai-libraries/microservices
          docker build -t dataprep-visualdata-milvus:latest -f visual-data-preparation-for-retrieval/milvus/src/Dockerfile .
          docker build -t retriever-milvus:latest -f vector-retriever/milvus/src/Dockerfile .
          cd vlm-openvino-serving
          docker build -t vlm-openvino-serving:latest -f docker/Dockerfile .
          cd ../../..
          cd metro-ai-suite
          docker build -t visual-search-qa-app:latest -f visual-search-question-and-answering/src/Dockerfile .

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          scan-type: 'fs'
          format: 'template'
          template: 'html'
          output: 'trivy_fs_report.html'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          command: '--skip-dirs node_modules'

      - name: Scan dataprep-visualdata-milvus image
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          scan-type: 'image'
          image-ref: 'dataprep-visualdata-milvus:latest'
          format: 'sarif'
          output: 'dataprep-visualdata-milvus.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Scan retriever-milvus image
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          scan-type: 'image'
          image-ref: 'retriever-milvus:latest'
          format: 'sarif'
          output: 'retriever-milvus.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Scan vlm-openvino-serving image
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          scan-type: 'image'
          image-ref: 'vlm-openvino-serving:latest'
          format: 'sarif'
          output: 'vlm-openvino-serving.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Scan visual-search-qa-app image
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          scan-type: 'image'
          image-ref: 'visual-search-qa-app:latest'
          format: 'sarif'
          output: 'visual-search-qa-app.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Upload scan results
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: trivy-scan-results
          path: |
            trivy_fs_report.html
            *.sarif

  bandit-scan:
    permissions:
      contents: read
      security-events: write  
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit Scan
        uses: orch-ci/bandit-action@67a458d90fa11fb1463e91e7f4c8f068b5863c7f
        with:
          target: 'metro-ai-suite/visual-search-question-and-answering/'
          output-format: 'sarif'
          output-file: 'bandit-report.sarif'
          severity-level: 'low,medium,high'  
          confidence-level: 'medium,high'    
          exclude-paths: '*/tests/*,*/migrations/*' 

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@7273f08caa1dcf2c2837f362f1982de0ab4dc344
        with:
          sarif_file: 'bandit-report.sarif'

      - name: Upload text report (optional)
        if: always()
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: bandit-text-report
          path: |
            bandit-report.sarif
        

  virus-scan:
    permissions:
      contents: read
      security-events: write  
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ClamAV Scan
        uses: orch-ci/clamav-action@293fa307caffa9b8742cb22ab3c31aa340083454
        with:
          target: 'metro-ai-suite/visual-search-question-and-answering/'
          output-format: 'sarif'
          output-file: 'clamav-report.sarif'
          db-update: true  
          max-filesize: '25M'  
          exclude: '*.log,*.tmp'  

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@7273f08caa1dcf2c2837f362f1982de0ab4dc344
        with:
          sarif_file: 'clamav-report.sarif'

      - name: Upload text report (optional)
        if: always()
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: clamav-text-report
          path: |
            clamav-report.sarif

