persistence:
  size: 20Gi

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/chunked-transfer-encoding: "on"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

  hosts:
    - host: health-ai.local
      paths:
        - path: /video-stream(/|$)(.*)
          pathType: ImplementationSpecific
          service: aggregator
          port: 8001

        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          service: aggregator
          port: 8001

        - path: /()(.*)
          pathType: ImplementationSpecific
          service: ui
          port: 80

  tls: []


ui:
  image:
    repository: intel
    name: hl-ai-ui
    tag: "latest"
    pullPolicy: Never

aggregator:
  image:
    repository: intel
    name: hl-ai-patient-monitoring-aggregator
    tag: "1.0.0"
    pullPolicy: Never

aiEcg:
  image:
    repository: intel
    name: hl-ai-ecg
    tag: "1.0.0"
    pullPolicy: Never

rppg:
  image:
    repository: intel
    name: hl-ai-rppg
    tag: "1.0.0"
    pullPolicy: Never

pose:
  image:
    repository: intel
    name: hl-ai-3dpose
    tag: "1.0.0"
    pullPolicy: Never

metrics:
  image:
    repository: intel
    name: hl-ai-metrics-collector
    tag: "1.0.0"
    pullPolicy: Never

ddsBridge:
  image:
    repository: intel
    name: hl-ai-dds-bridge
    tag: "1.0.0"
    pullPolicy: Never

mdpnp:
  image:
    repository: intel
    name: hl-ai-mdpnp
    tag: "1.0.0"
    pullPolicy: Never

assets:
  image:
    repository: intel
    name: hl-ai-patient-monitoring-assets
    tag: "1.0.0"
    pullPolicy: Never

devices:
  ECG_DEVICE: "GPU"
  RPPG_DEVICE: "GPU"
  MDPNP_DEVICE: "CPU"
  POSE_3D_DEVICE: "GPU"
